lang: ru
fail-if-warnings: true
project:
  type: website
  output-dir: _site
  render: [index.qmd]
  pre-render: _extensions/Afonenko-Course-Tools/course-site/entrypoints/pre.ts
  post-render: _extensions/Afonenko-Course-Tools/course-site/entrypoints/post.ts
profile:
  default: full
website:
  repo-url: https://github.com/Afonenko-Course-Tools/quarto-project-publish
  repo-branch: demo-20261007-ru1
  repo-subdir: examples/course/
  repo-actions: [source]
  title: Составной курс
  navbar:
    right:
      - text: Исходники проекта
        href: https://github.com/Afonenko-Course-Tools/quarto-project-publish/tree/demo-20261007-ru1/examples/course/
format: html
filters: [reference-catalog]
reference-catalog: {namespace: portal}
subprojects: [book, materials]
