project:
  type: website
  output-dir: _site
  render: []
website:
  title: Материалы курса
format:
  html:
    theme: cosmo
lang: ru
filters:
  - reference-catalog
reference-catalog:
  namespace: site
  home: book
  exports:
    book: "*"
    lectures: "*"
    practice: "*"
  projects:
    book:
      path: book
      format: html
    lectures:
      path: lectures
      format: revealjs
    practice:
      path: practice
      format: revealjs
