lang: ru
fail-if-warnings: true
project:
  type: website
  output-dir: _site
  render: [notes.qmd, slides.qmd]
  post-render:
    - _extensions/Afonenko-Course-Tools/reference-catalog/entrypoints/post.ts
    - ../_extensions/Afonenko-Course-Tools/course-site/entrypoints/collect.ts
profile:
  default: full
format: html
bibliography: ../references.bib
filters: [reference-catalog]
reference-catalog: {namespace: study}
website:
  repo-url: https://github.com/Afonenko-Course-Tools/quarto-project-publish
  repo-branch: v4.0.0
  repo-subdir: examples/course/materials
  repo-actions: [source]
  navbar:
    right:
      - text: Исходники проекта
        href: https://github.com/Afonenko-Course-Tools/quarto-project-publish/tree/v4.0.0/examples/course/materials
