project:
  type: book
  output-dir: _site
  post-render:
    - _extensions/reference-catalog/entrypoints/post.ts
    - ../_extensions/course-site/entrypoints/collect.ts
profile:
  default: full
book:
  title: Теория
format: html
bibliography: ../references.bib
filters: [reference-catalog]
reference-catalog: {namespace: theory}
