lang: ru
fail-if-warnings: true
project:
  type: book
  output-dir: _site
  post-render:
    - _extensions/Afonenko-Course-Tools/reference-catalog/entrypoints/post.ts
    - ../_extensions/Afonenko-Course-Tools/course-site/entrypoints/collect.ts
profile:
  default: full
book:
  repo-url: https://github.com/Afonenko-Course-Tools/quarto-project-publish
  repo-branch: demo-20261007-ru1
  repo-subdir: examples/course/book
  repo-actions: [source]
  title: Теория
  sidebar:
    tools:
      - icon: github
        text: Исходники проекта
        href: https://github.com/Afonenko-Course-Tools/quarto-project-publish/tree/demo-20261007-ru1/examples/course/book
format: html
bibliography: ../references.bib
filters: [reference-catalog]
reference-catalog: {namespace: theory}
